version: "3.9"

services:

  # BASE DE DATOS
  pg_db_movies:
    container_name: 'pg_db_movies'
    restart: always
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=strong-password
      - POSTGRES_USER=dfz
      - POSTGRES_DB=db_movies
    networks:
      - knn_service_net
    volumes:
      - ./api/config/database/pg:/docker-entrypoint-initdb.d

  # PG ADMIN
  pgadmin_movies:
    image: dpage/pgadmin4
    container_name: 'pgadmin_movies'
    restart: always
    ports: 
      - "127.0.0.1:8081:80" 
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes: 
      - ./api/config/pg/servers.json:/pgadmin4/servers.json
    networks:
      - knn_service_net

# API FLASK
  movies_api:
    container_name: 'movies_api'
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - pg_db_movies
    environment:
      - DB_HOST=pg_db_movies
      - DB_PORT=5432
      - DB_USER=dfz
      - DB_PASSWORD=strong-password
      - DB_NAME=db_movies
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - knn_service_net
    volumes:
      - ./api:/app

# New React frontend service
  react_frontend:
    container_name: 'react_frontend'
    build:
      context: ./app/webapp-seminarioia
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"  # Cambiado a 5173 para Vite
    volumes:
      - ./app/webapp-seminarioia:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=https://proyecto-d1.site/api
    depends_on:
      - movies_api
    networks:
      - knn_service_net

networks:
  knn_service_net:
    driver: bridge